---
  TPPOAuth2Security: 
    type: "oauth2"
    flow: "application"
    tokenUrl: "https://authserver.example/token"
    scopes: 
      payments: "Generic payment scope"
    description: "TPP client credential authorisation flow with the ASPSP"
