TPPOAuth2Security:
  type: oauth2
  flow: application
  tokenUrl: 'https://authserver.example/token'
  scopes:
    fundsconfirmations: Funds confirmation entitlement
  description: TPP client credential authorisation flow with the ASPSP
