swagger: '2.0'

info:
  title: Account and Transaction API Specification
  description: Swagger for Account and Transaction API Specification
  termsOfService: 'https://www.openbanking.org.uk/terms'
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: 'https://www.openbanking.org.uk/open-licence'
  version: v2.0.0

basePath: /open-banking/v2.0

tags:
- name: "Account Requests"
  description: "Account Requests"
- name: "Accounts"
  description: "Accounts"
- name: "Transactions"
  description: "Transactions"
- name: "Beneficiaries"
  description: "Beneficiaries"
- name: "Balances"
  description: "Balances"
- name: "Direct Debits"
  description: "Direct Debits"
- name: "Standing Orders"
  description: "Standing Orders"
- name: "Products"
  description: "Products"

schemes: [https]

consumes: [application/json; charset=utf-8]
produces: [application/json; charset=utf-8]

paths:
  /account-requests:
    - $ref: ./paths/CreateAccountRequest.yaml
  /account-requests/{AccountRequestId}:
    - $ref: ./paths/GetAccountRequest.yaml
    - $ref: ./paths/DeleteAccountRequest.yaml
  /accounts:
    - $ref: ./paths/GetAccounts.yaml
  /accounts/{AccountId}:
    - $ref: ./paths/GetAccount.yaml
  /accounts/{AccountId}/transactions:
    - $ref: ./paths/GetAccountTransactions.yaml
  /accounts/{AccountId}/beneficiaries:
    - $ref: ./paths/GetAccountBeneficiaries.yaml
  /accounts/{AccountId}/balances:
    - $ref: ./paths/GetAccountBalances.yaml
  /accounts/{AccountId}/direct-debits:
    - $ref: ./paths/GetAccountDirectDebits.yaml
  /accounts/{AccountId}/standing-orders:
    - $ref: ./paths/GetAccountStandingOrders.yaml
  /accounts/{AccountId}/product:
    - $ref: ./paths/GetAccountProduct.yaml
  /accounts/{AccountId}/offers:
    - $ref: ./paths/GetAccountOffers.yaml
  /accounts/{AccountId}/party:
    - $ref: ./paths/GetAccountParty.yaml
  /accounts/{AccountId}/scheduled-payments:
    - $ref: ./paths/GetAccountScheduledPayments.yaml
  /accounts/{AccountId}/statements:
    - $ref: ./paths/GetAccountStatements.yaml
  /accounts/{AccountId}/statements/{StatementId}:
    - $ref: ./paths/GetAccountStatement.yaml
  /accounts/{AccountId}/statements/{StatementId}/file:
    - $ref: ./paths/GetAccountStatementFile.yaml
  /accounts/{AccountId}/statements/{StatementId}/transactions:
    - $ref: ./paths/GetAccountStatementTransactions.yaml
  /standing-orders:
    - $ref: ./paths/GetStandingOrders.yaml
  /direct-debits:
    - $ref: ./paths/GetDirectDebits.yaml
  /beneficiaries:
    - $ref: ./paths/GetBeneficiaries.yaml
  /transactions:
    - $ref: ./paths/GetTransactions.yaml
  /balances:
    - $ref: ./paths/GetBalances.yaml
  /products:
    - $ref: ./paths/GetProducts.yaml
  /offers:
    - $ref: ./paths/GetOffers.yaml
  /party:
    - $ref: ./paths/GetParty.yaml
  /scheduled-payments:
    - $ref: ./paths/GetScheduledPayments.yaml
  /statements:
    - $ref: ./paths/GetStatements.yaml

definitions:
  - $ref: ./definitions/AccountId.yaml
  - $ref: ./definitions/Amount.yaml
  - $ref: ./definitions/CurrencyAndAmount.yaml
  - $ref: ./definitions/OBAccount2.yaml
  - $ref: ./definitions/OBAccount2Basic.yaml
  - $ref: ./definitions/OBAccount2Detail.yaml
  - $ref: ./definitions/OBAddressTypeCode.yaml
  - $ref: ./definitions/OBBalanceType1Code.yaml
  - $ref: ./definitions/OBBankTransactionCodeStructure1.yaml
  - $ref: ./definitions/OBBeneficiary2.yaml
  - $ref: ./definitions/OBBeneficiary2Basic.yaml
  - $ref: ./definitions/OBBeneficiary2Detail.yaml
  - $ref: ./definitions/OBBranchAndFinancialInstitutionIdentification2.yaml
  - $ref: ./definitions/OBBranchAndFinancialInstitutionIdentification3.yaml
  - $ref: ./definitions/OBCashAccount1.yaml
  - $ref: ./definitions/OBCashAccount2.yaml
  - $ref: ./definitions/OBCashBalance1.yaml
  - $ref: ./definitions/OBCreditDebitCode.yaml
  - $ref: ./definitions/OBCreditLine1.yaml
  - $ref: ./definitions/OBDirectDebit1.yaml
  - $ref: ./definitions/OBEntryStatus1Code.yaml
  - $ref: ./definitions/OBExternalAccountIdentification3Code.yaml
  - $ref: ./definitions/OBExternalAccountSubType1Code.yaml
  - $ref: ./definitions/OBExternalAccountType1Code.yaml
  - $ref: ./definitions/OBExternalCardAuthorisationType1Code.yaml
  - $ref: ./definitions/OBExternalCardSchemeType1Code.yaml
  - $ref: ./definitions/OBExternalDirectDebitStatus1Code.yaml
  - $ref: ./definitions/OBExternalFinancialInstitutionIdentification2Code.yaml
  - $ref: ./definitions/OBExternalLimitType1Code.yaml
  - $ref: ./definitions/OBExternalOfferType1Code.yaml
  - $ref: ./definitions/OBExternalPartyType1Code.yaml
  - $ref: ./definitions/OBExternalPermissions1Code.yaml
  - $ref: ./definitions/OBExternalProductType1Code.yaml
  - $ref: ./definitions/OBExternalScheduleType1Code.yaml
  - $ref: ./definitions/OBExternalStandingOrderStatus1Code.yaml
  - $ref: ./definitions/OBExternalStatementAmountType1Code.yaml
  - $ref: ./definitions/OBExternalStatementBenefitType1Code.yaml
  - $ref: ./definitions/OBExternalStatementDateTimeType1Code.yaml
  - $ref: ./definitions/OBExternalStatementFeeType1Code.yaml
  - $ref: ./definitions/OBExternalStatementInterestType1Code.yaml
  - $ref: ./definitions/OBExternalStatementRateType1Code.yaml
  - $ref: ./definitions/OBExternalStatementType1Code.yaml
  - $ref: ./definitions/OBExternalStatementValueType1Code.yaml
  - $ref: ./definitions/OBMerchantDetails1.yaml
  - $ref: ./definitions/OBOffer1.yaml
  - $ref: ./definitions/OBParty1.yaml
  - $ref: ./definitions/OBPostalAddress8.yaml
  - $ref: ./definitions/OBProduct2.yaml
  - $ref: ./definitions/OBReadAccount2.yaml
  - $ref: ./definitions/OBReadBalance1.yaml
  - $ref: ./definitions/OBReadBeneficiary2.yaml
  - $ref: ./definitions/OBReadData1.yaml
  - $ref: ./definitions/OBReadDataResponse1.yaml
  - $ref: ./definitions/OBReadDirectDebit1.yaml
  - $ref: ./definitions/OBReadOffer1.yaml
  - $ref: ./definitions/OBReadParty1.yaml
  - $ref: ./definitions/OBReadProduct2.yaml
  - $ref: ./definitions/OBReadRequest1.yaml
  - $ref: ./definitions/OBReadResponse1.yaml
  - $ref: ./definitions/OBReadScheduledPayment1.yaml
  - $ref: ./definitions/OBReadStandingOrder2.yaml
  - $ref: ./definitions/OBReadStatement1.yaml
  - $ref: ./definitions/OBReadTransaction2.yaml
  - $ref: ./definitions/OBScheduledPayment1.yaml
  - $ref: ./definitions/OBScheduledPayment1Basic.yaml
  - $ref: ./definitions/OBScheduledPayment1Detail.yaml
  - $ref: ./definitions/OBStandingOrder2.yaml
  - $ref: ./definitions/OBStandingOrder2Basic.yaml
  - $ref: ./definitions/OBStandingOrder2Detail.yaml
  - $ref: ./definitions/OBStatement1.yaml
  - $ref: ./definitions/OBStatement1Basic.yaml
  - $ref: ./definitions/OBStatement1Detail.yaml
  - $ref: ./definitions/OBStatementAmount1.yaml
  - $ref: ./definitions/OBStatementBenefit1.yaml
  - $ref: ./definitions/OBStatementDateTime1.yaml
  - $ref: ./definitions/OBStatementFee1.yaml
  - $ref: ./definitions/OBStatementInterest1.yaml
  - $ref: ./definitions/OBStatementRate1.yaml
  - $ref: ./definitions/OBStatementValue1.yaml
  - $ref: ./definitions/OBTransaction2.yaml
  - $ref: ./definitions/OBTransaction2Basic.yaml
  - $ref: ./definitions/OBTransaction2Detail.yaml
  - $ref: ./definitions/OBTransactionCardInstrument1.yaml
  - $ref: ./definitions/OBTransactionCashBalance.yaml
  - $ref: ./definitions/OB_OtherProductType1.yaml
  - $ref: ./definitions/OBPCAData1.yaml
  - $ref: ./definitions/OBBCAData1.yaml
  - $ref: ./definitions/TransactionInformation.yaml

  - $ref: ./definitions/OBExternalRequestStatus1Code.yaml
  - $ref: ./definitions/OBExternalAccountIdentification2Code.yaml

  - $ref: ../readwrite/definitions/OBRisk2.yaml
  - $ref: ../readwrite/definitions/Links.yaml
  - $ref: ../readwrite/definitions/ISODateTime.yaml
  - $ref: ../readwrite/definitions/Meta.yaml

parameters:
  - $ref: ./parameters/AcceptParam.yaml
  - $ref: ./parameters/AccountIdParam.yaml
  - $ref: ./parameters/AccountRequestIdParam.yaml
  - $ref: ./parameters/FromBookingDateTimeParam.yaml
  - $ref: ./parameters/OBReadRequest1Param.yaml
  - $ref: ./parameters/StatementIdParam.yaml
  - $ref: ./parameters/ToBookingDateTimeParam.yaml
  - $ref: ../readwrite/parameters/x-fapi-financial-id-Param.yaml
  - $ref: ../readwrite/parameters/x-fapi-customer-ip-address-Param.yaml
  - $ref: ../readwrite/parameters/x-fapi-interaction-id-Param.yaml
  - $ref: ../readwrite/parameters/x-fapi-customer-last-logged-time-Param.yaml
  - $ref: ../readwrite/parameters/AuthorizationParam.yaml
  - $ref: ../readwrite/parameters/x-jws-signature-Param.yaml

responses:
  - $ref: ./responses/200AccountBalancesRead.yaml
  - $ref: ./responses/200AccountBeneficiariesRead.yaml
  - $ref: ./responses/200AccountDirectDebitsRead.yaml
  - $ref: ./responses/200AccountOffersRead.yaml
  - $ref: ./responses/200AccountPartyRead.yaml
  - $ref: ./responses/200AccountProductRead.yaml
  - $ref: ./responses/200AccountRead.yaml
  - $ref: ./responses/200AccountRequestRead.yaml
  - $ref: ./responses/200AccountScheduledPaymentsRead.yaml
  - $ref: ./responses/200AccountStandingOrdersRead.yaml
  - $ref: ./responses/200AccountStatementFileRead.yaml
  - $ref: ./responses/200AccountStatementsRead.yaml
  - $ref: ./responses/200AccountTransactionsRead.yaml
  - $ref: ./responses/201AccountRequestCreated.yaml
  - $ref: ./responses/204AccountRequestDeleted.yaml
  - $ref: ../readwrite/responses/400ErrorResponse.yaml
  - $ref: ../readwrite/responses/401ErrorResponse.yaml
  - $ref: ../readwrite/responses/403ErrorResponse.yaml
  - $ref: ../readwrite/responses/405ErrorResponse.yaml
  - $ref: ../readwrite/responses/406ErrorResponse.yaml
  - $ref: ../readwrite/responses/429ErrorResponse.yaml
  - $ref: ../readwrite/responses/500ErrorResponse.yaml

securityDefinitions:
  - $ref: ../readwrite/securityDefinitions/PSUOAuth2Security.yaml
  - $ref: ../readwrite/securityDefinitions/TPPOAuth2Security.yaml
