get:
  summary: Get Products
  description: Get Products
  operationId: GetProducts
  produces:
    - $ref: ../../definitions/mime_type.yaml
  responses:
    200:
      description: Products successfully retrieved
      schema:
        $ref: ../../../../../compiled/schemas/v0/products/products.get.200.response.schema.yaml
    400:
      $ref: ../../index.yaml#/responses/400ErrorResponse
    401:
      $ref: ../../index.yaml#/responses/401ErrorResponse
    403:
      $ref: ../../index.yaml#/responses/403ErrorResponse
    404:
      $ref: ../../index.yaml#/responses/404NotFound
    500:
      $ref: ../../index.yaml#/responses/500ErrorResponse
  security:
    - PSUOAuth2Security:
      - products:read
